# Use the official WordPress image as the base image
FROM wordpress:latest

# Set the environment variables for MySQL connection
ENV WORDPRESS_DB_HOST=mysql
ENV WORDPRESS_DB_USER=root
ENV WORDPRESS_DB_PASSWORD=your_mysql_password
ENV WORDPRESS_DB_NAME=wordpress

# Install the mysqli extension for PHP
RUN docker-php-ext-install mysqli

# Copy custom configuration file to the container
COPY wp-config.php /var/www/html/wp-config.php